services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.7-alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - vhost:/etc/nginx/vhost.d
      - conf:/etc/nginx/conf.d
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    networks:
      - nginx-proxy-network    


  nginx-proxy-acme:
    image: nginxproxy/acme-companion:2.5.2
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=raulodev@gmail.com
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - vhost:/etc/nginx/vhost.d
      - conf:/etc/nginx/conf.d
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro

    networks:
      - nginx-proxy-network
    restart: always      


networks:
  nginx-proxy-network:
    driver: bridge      

volumes:
  certs:
  html:
  acme:
  vhost:
  conf: